### ISSUE TITLE
URL regex causing syntax errors in mobile safari

### ISSUE THREAD

**Issue by Noitidart** [anantoghosh/react-linkify-it#21]
This regex here is causing a syntax error in some browsers. https://github.com/anantoghosh/react-linkify-it/blob/bfd9debe1b005494b60851abca54faf7abbed910/src/url.tsx#L4-L5

The error is:

> Invalid regular expression: invalid escaped character for unicode pattern

The browsers I got errors in so far are:

Mobile Safari 10.0
Mobile Safari 13.1.2

I'm not sure how to fix it exactly. :(

**Comment by anantoghosh** [comment]
This regex will not work on mobile safari 10 for sure, if you are not using babel env preset to transform the regex, then this will happen.
I'm not sure why safari 13 throws an error.
Try using the legacy bundle https://github.com/anantoghosh/react-linkify-it#using-modern-and-legacy-bundle.

**Comment by anantoghosh** [comment]
does it work with iOS safari 11.3 - 12.x?

**Comment by anantoghosh** [comment]
[Babel repl.](https://babeljs.io/repl/#?browsers=iOS%2010&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBArgJwDYCUCmBzNAPGBeAKBhgHoAKACyigAcIB-ALgB0TWAfAd2-YDoBKMgG0AtM068AugGpWQ5jQDeAGQC-CxQFEAtiABWAS3VKd-gwH0AwiG01waMFFUBCAMQASAKQAyAOQAiMn4AKmkAGl42ZkYAbjxzegABeUkAPxFJYKEAPWYIAIiYlgAjfmZJVXpJdjJhcQzZAWl5TgaWkgz-fhI4GKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=7.17.9&externalPlugins=&assumptions=%7B%7D)

Since you had posted that you had issues with importing legacy bundle in next.js:
Try the transformed regex and use it with the exported `UrlComponent`.

**Comment by Noitidart** [comment]
Thanks for the fast reply! I don't have any other device than the iOS 10. The error came from prod :( But verified in iOS 10 that babel thing works! Thanks!
